name: pull request

on:
  pull_request:
    branches: ["main"]

jobs:
  quality:
    uses: ./.github/workflows/_quality.yaml
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: AI Code Reviewer
        uses: matheusaraujo/ai-code-reviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
